version: '3.7'

services:
  server:
    image: nginx
    container_name: ninja_server
    restart: always
    env_file: docker-compose.env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ./docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "8083:80"
      # - "44392:443"
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.1.40" #host and ip

  app:
    image: invoiceninja/invoiceninja:5
    container_name: ninja_app
    env_file: docker-compose.env
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.1.40" #host and ip

  db:
    image: mysql:8
    container_name: ninja_db
    #    When running on ARM64 use MariaDB instead of MySQL
    #    image: mariadb:10.4
    #    For auto DB backups comment out image and use the build block below
    #    build:
    #      context: ./config/mysql
    ports:
      - "3305:3306"
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
      # remove comments for next 4 lines if you want auto sql backups
      #- ./docker/mysql/bak:/backups:rw
      #- ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      #- ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      #- ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
    networks:
      - invoiceninja
    extra_hosts:
      - "in5.localhost:192.168.1.40" #host and ip

networks:
  invoiceninja:
    name: invoiceninja
